header: "&5Ultimate&9Tablist\n &aWelcome to &6Server.com\n{date} {time}:{seconds}"
footer: "&aCheck out our store &6>> &aStore.com\n&aOnline: &6{players}"
localhost: true
ipdatakey: ""
###IF EITHER OF THE TWO ABOVE ARE FALSE OR NOT FILLED IN YOU NEED TO SET THIS
timezone: "Europe/Berlin"
#You can use this to find your Timezone: https://www.timeanddate.com/time/map/
#Use the normal Minecraft color codes with & before them.
#minecraft.tools/en/color-code.php
#Use \n to insert a linebreak.
#Use {players} to insert a player count.
#Use {time} to insert the current time.
#Use {seconds} to insert the current second.
#Use {date} to insert the current date.
#Use {weekday} to insert the current weekday.
#Use {month} to insert the current month.
#IMPORTANT
#Using the time features may result in a small performance loss, so use them wisely.

#IPDATAKEY EXPLANATION
#In there you can put your ipdata.co key, to make the time displayed to be set for each player according to thier time
#Zone, if you don't want to use this, !!!LEAVE IT BLANK!!!;