name: UltimateTablist
version: 1.3
main: de.h3xabyt3.ultimatetablist.UltimateTablist
api-version: 1.18
authors: [ H3xabyt3 ]
description: The easiest way to make a custom Tablist with all sorts of functions!
libraries:
  - co.ipdata.client:ipdata-java-client:0.2.0
  - org.json:json:20231013